# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeEassy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeEassy
pod 'IQKeyboardManagerSwift'
pod "Mobile-Buy-SDK"

pod 'MaterialComponents/TextControls+FilledTextFields'
pod 'ReachabilitySwift'
pod 'Kingfisher', '~> 7.0'
pod 'DGActivityIndicatorView'
pod 'ObjectMapper'
pod 'Firebase'
pod 'Firebase/Crashlytics'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'SwiftGifOrigin', '~> 1.7.0'
pod 'SnapKit'
pod 'lottie-ios'
pod 'SkeletonView'
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end

#pod 'IDMPhotoBrowser'
end
